export const copy = {
  event: {
    name: "crabhacks",
    tagline: "the largest high school hackathon in the dmv area",
    year: "2025",
    description: "join us for a day of innovation, collaboration, and creativity. whether you're building your first project or your hundredth, crabhacks is the perfect place to bring your ideas to life.",
    longDescription: "crabhacks brings together the brightest high school students from across the dmv region for an unforgettable day of building, learning, and connecting. compete for prizes, learn from industry mentors, and connect with fellow builders—all while creating something amazing.",
  },
  dates: {
    start: "december 7, 2025",
    end: "december 7, 2025",
    duration: "10 hours",
    registrationDeadline: "december 3, 2025",
    checkIn: "sunday 9:00 am",
    kickoff: "sunday 9:30 am",
    closing: "sunday 7:00 pm",
  },
  location: {
    venue: "bethesda, md",
    address: "bethesda, md",
    fullAddress: "4701 Sangamore Rd Suite 100N, Bethesda, MD 20816",
    directions: "located in bethesda, easily accessible by metro, car, or bus. parking available nearby.",
  },
  stats: {
    participants: 300,
    projects: 80,
    sponsors: 15,
    prizes: 1000,
  },
  cta: {
    primary: "register now",
    secondary: "apply as a mentor",
    tertiary: "become a sponsor",
    learnMore: "learn more",
  },
  info: {
    format: "10-hour hackathon",
    teamSize: "teams of 1–4",
    free: "completely free",
    food: "all meals provided",
    swag: "free swag for all participants",
    prizes: "$1,000+ in prizes",
    workshops: "workshops for all skill levels",
    mentors: "experienced mentors available",
  },
  faq: [
    {
      question: "do i need to be a high school student?",
      answer: "yes, crabhacks is open to all current high school students (grades 9–12) in the dmv area.",
    },
    {
      question: "do i need coding experience?",
      answer: "not at all! we welcome participants of all skill levels. we'll have workshops, mentors, and resources to help you build something amazing.",
    },
    {
      question: "how much does it cost?",
      answer: "crabhacks is completely free! we provide food, swag, prizes, and an amazing experience at no cost to you.",
    },
    {
      question: "do i need a team?",
      answer: "nope! you can come solo and we'll help you find a team, or come with your own team of up to 4 people.",
    },
    {
      question: "what should i bring?",
      answer: "bring your laptop, charger, valid student id, and excitement to build! we'll provide everything else including food, drinks, and a place to hack.",
    },
    {
      question: "can i use past projects?",
      answer: "all projects must be started during the hackathon. you can plan ahead, but code must be written during the event.",
    },
    {
      question: "what are the prizes?",
      answer: "we have over $1,000 in prizes across multiple categories including best overall, best design, best use of sponsor apis, and more!",
    },
    {
      question: "will there be workshops?",
      answer: "yes! we'll have workshops throughout the day covering topics from beginner web development to advanced machine learning.",
    },
  ],
  sponsors: [
    { name: "acme corp", tier: "platinum" },
    { name: "tech solutions inc", tier: "gold" },
    { name: "digital innovations", tier: "gold" },
    { name: "code masters", tier: "silver" },
    { name: "dev labs", tier: "silver" },
    { name: "startup hub", tier: "silver" },
    { name: "cloud systems", tier: "bronze" },
    { name: "data analytics co", tier: "bronze" },
    { name: "mobile first", tier: "bronze" },
    { name: "web services", tier: "bronze" },
  ],
  schedule: [
    { time: "sunday 9:00 am", event: "check-in & breakfast", day: "sunday" },
    { time: "sunday 9:30 am", event: "opening ceremony & kickoff", day: "sunday" },
    { time: "sunday 10:00 am", event: "hacking begins", day: "sunday" },
    { time: "sunday 12:00 pm", event: "lunch", day: "sunday" },
    { time: "sunday 1:00 pm", event: "workshop session", day: "sunday" },
    { time: "sunday 3:00 pm", event: "afternoon snack break", day: "sunday" },
    { time: "sunday 4:00 pm", event: "mentor office hours", day: "sunday" },
    { time: "sunday 5:00 pm", event: "hacking ends & submissions due", day: "sunday" },
    { time: "sunday 5:30 pm", event: "judging & demos", day: "sunday" },
    { time: "sunday 6:30 pm", event: "closing ceremony & prizes", day: "sunday" },
    { time: "sunday 7:00 pm", event: "event ends", day: "sunday" },
  ],
  tracks: [
    { name: "web development", icon: "globe" },
    { name: "mobile apps", icon: "smartphone" },
    { name: "ai/ml", icon: "brain" },
    { name: "hardware", icon: "zap" },
    { name: "devops", icon: "cloud" },
    { name: "blockchain", icon: "link" },
  ],
};
